<?php

/**
 * PluginsfVkontakteFriendshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfVkontakteFriendshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfVkontakteFriendshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfVkontakteFriendship');
    }
}