<?php

/**
 * PluginFriendReferenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFriendReferenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFriendReferenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFriendReference');
    }
}