<?php

/**
 * PluginsfVkontakteUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfVkontakteUser extends BasesfVkontakteUser
{
	public function getNeedFetchFriends() {
		return ($this->fetched_at < date('Y-m-d'));
	}
}
