<?php

/**
 * PluginsfVkontakteUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfVkontakteUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfVkontakteUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfVkontakteUser');
    }
}